#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL

    -- NEST
    CREATE USER $NEST_DB_USER WITH PASSWORD '$NEST_DB_PASS' LOGIN;
    CREATE DATABASE $NEST_DB_NAME OWNER $NEST_DB_USER;

    -- Logto
    CREATE USER $LOGTO_DB_USER WITH PASSWORD '$LOGTO_DB_PASS';
    ALTER USER $LOGTO_DB_USER CREATEROLE;
    CREATE DATABASE $LOGTO_DB_NAME OWNER $LOGTO_DB_USER;

EOSQL